#!/usr/bin/env ruby
require "bundler/setup"
require "librato/memcached"

Librato::Metrics.authenticate ENV["LIBRATO_EMAIL"], ENV["LIBRATO_TOKEN"]

queue = Librato::Metrics::Queue.new

loop do
  # collect and queue metrics
  Librato::Memcached.collect!(queue)

  begin
    # submit to Librato
    queue.submit
  rescue Exception => e
    $stderr.puts e
  end

  # do another collection in 60 seconds
  sleep(60)
end
