#!/usr/bin/env ruby
require "logger"

require "bundler/setup"
require "librato/memcached"

logger = Logger.new(STDOUT)

email = ENV["LIBRATO_EMAIL"]
token = ENV["LIBRATO_TOKEN"]

logger.info "Authenticating with email: #{email}"
logger.info "Authenticating with API token: #{token}"

Librato::Metrics.authenticate(email, token)

logger.info "Creating metrics queue"
queue = Librato::Metrics::Queue.new

loop do
  logger.info "Starting metrics collection..."
  # collect and queue metrics
  Librato::Memcached.collect!(queue)

  begin
    logger.info "Submitting metrics to Librato!"
    queue.submit
  rescue Exception => e
    $stderr.puts e
  end

  # do another collection in 60 seconds
  sleep(60)
end
